language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install python-numpy python-scipy
 - sudo apt-get --no-install-recommends install python-pandas>=0.12.0
 - sudo apt-get --no-install-recommends install python-pandas-lib
# - pip install patsy

install:
  - pip install patsy
  - pip install git+http://github.com/enthought/traits.git#egg=traits
   # - pip install git+http://github.com/enthought/traits.git#egg=traits
   # - pip install git+http://github.com/enthought/traitsui.git#egg=traitsui
   # - pip install git+http://github.com/enthought/enable.git#egg=enable
  - easy_install -U statsmodels=0.4.3
#  - pip install -r requirements.txt
  - python setup.py develop

# command to run tests, e.g. python setup.py test
script:  python setup.py test