language: python
notifications:
  email: False
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install xvfb
 #- sudo apt-get --no-install-recommends install python-pandas>=0.12.0
 #- sudo apt-get --no-install-recommends install python-pandas-lib
# - pip install patsy

install:
  #- sudo apt-get install python-pyside
  - pip install cython
  - sudo apt-get install python-numpy python-scipy
  - sudo apt-get install swig
  - pip install PIL --allow-external PIL --allow-unverified PIL
  - pip install pyparsing
  - pip install patsy
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  #- pip install git+http://github.com/enthought/pyface.git#egg=pyface
  - pip install git+http://github.com/enthought/traitsui.git#egg=traitsui
  #- pip install git+http://github.com/enthought/enable.git#egg=enable

  #install pandas from source
  #- pip install Cython>=0.16
  #- git clone git://github.com/pydata/pandas.git
  #- cd pandas
  #- git checkout v0.12.0
  #- python setup.py install
  #- cd ..

  - pip install -r requirements.txt
  #- python setup.py develop

# command to run tests, e.g. python setup.py test
#script: DISPLAY=localhost:1.0 xvfb-run python setup.py test
script: python setup.py test