sudo: false
language: python
notifications:
  slack: nmgrl:ols00MOM4n3EimDpMiluJIyF
  email:
    on_failure: change


env:
  # Default values for common packages, override as needed
  global:
    - PYTHON=3.5

python:
  - ${PYTHON}

before_install:
  - export TZ=America/Denver
  # adapted from statsmodels travis file https://github.com/statsmodels/statsmodels/blob/master/.travis.yml
  # setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Build package list to avoid empty package=versions; only needed for versioned pacakges
#  - PKGS="python=${PYTHON}"
#  - PKGS="${PKGS} numpy"; if [ ${NUMPY} ]; then PKGS="${PKGS}=${NUMPY}"; fi
#  - PKGS="${PKGS} scipy"; if [ ${SCIPY} ]; then PKGS="${PKGS}=${SCIPY}"; fi
#  - PKGS="${PKGS} patsy"; if [ ${PATSY} ]; then PKGS="${PKGS}=${PATSY}"; fi
#  - PKGS="${PKGS} pandas"; if [ ${PANDAS} ]; then PKGS="${PKGS}=${PANDAS}"; fi
#  - PKGS="${PKGS} Cython"; if [ ${CYTHON} ]; then PKGS="${PKGS}=${CYTHON}"; fi
#  - PKGS="${PKGS} pip";

install:
#  - conda create --yes --quiet -n pychron-test ${PKGS} ${OPTIONAL}
  - conda create --yes --quiet -n pychron-test python=${PYTHON}
  - source activate pychron-test

  - CONDA_PKGS=statsmodels PyYAML chaco xlrd xlwt lxml apptools
  - conda install --yes ${CONDA_PKGS}
  - PIP_PKGS=uncertainties pint codecov coverage
  - pip install ${PIP_PKGS}

#script: python setup.py test
script: coverage run setup.py test
after_success:
  - codecov