language: python
notifications:
  email: False
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#virtualenv:
#  system_site_packages: true
env:
  # Default values for common packages, override as needed
  global:
    - CYTHON=0.20
    - PATSY=0.2
    - PANDAS=0.12
    #- MATPLOTLIB=false
    - OPTIONAL=
    - COVERAGE=false
    - PYTHON=2.7

before_install:
  # adapted from statsmodels travis file https://github.com/statsmodels/statsmodels/blob/master/.travis.yml
  # setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Avoid noise from matplotlib
  #- mkdir $HOME/.config
  #- mkdir $HOME/.config/matplotlib
  #- SRCDIR=$PWD
  #- cp $SRCDIR/tools/matplotlibrc $HOME/.config/matplotlib/matplotlibrc
  # Location for older version of matplotlib
  #- if [ ${MATPLOTLIB} = "1.2" ]; then mkdir $HOME/.matplotlib; fi
  #- if [ ${MATPLOTLIB} = "1.2" ]; then cp ${SRCDIR}/tools/matplotlibrc $HOME/.matplotlib/matplotlibrc; fi
  # Build package list to avoid empty package=versions; only needed for versioned pacakges
  - PKGS="python=${PYTHON}"
  - PKGS="${PKGS} numpy"; if [ ${NUMPY} ]; then PKGS="${PKGS}=${NUMPY}"; fi
  - PKGS="${PKGS} scipy"; if [ ${SCIPY} ]; then PKGS="${PKGS}=${SCIPY}"; fi
  - PKGS="${PKGS} patsy"; if [ ${PATSY} ]; then PKGS="${PKGS}=${PATSY}"; fi
  - PKGS="${PKGS} pandas"; if [ ${PANDAS} ]; then PKGS="${PKGS}=${PANDAS}"; fi
  - PKGS="${PKGS} Cython"; if [ ${CYTHON} ]; then PKGS="${PKGS}=${CYTHON}"; fi
  #- PKGS="${PKGS} matplotlib"; if [ ${MATPLOTLIB} ]; then PKGS="${PKGS}=${MATPLOTLIB}"; fi

install:
  - conda create --yes --quiet -n pychron-test ${PKGS} ${OPTIONAL} pip
  - source activate pychron-test
  - pip install -r requirements.txt
  #- python setup.py test

script: python setup.py test