### GENERAL SETTINGS ###

# Site settings
title: Pychron.
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/pychron" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 801 Leroy Place
    - 87801, Socorro, NM
    - United States.
email: jross@nmbgmr.nmt.edu
tel: 575-835-5081


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Jake Ross, PhD
    position: Founder, Lead Developer
    text: Founder, Lead Developer for Pychron Labs, LLC
    img: ross.jpg
    social:
      - title: envelope #use for email address
        url: mailto:jross@nmbgmr.nmt.edu
      - title: github
        url: http://github.com/jirhiker
  - name: William McIntosh, PhD
    position: Director
    text: Director of NMGRL
    img: mcintosh.jpg
    social:
      - title: envelope #use for email address
        url: mailto:mcintosh@nmt.edu
  - name: Matt Heizler, PhD
    position: Director
    text: Director of NMGRL
    img: heizler.jpg
    social:
      - title: envelope #use for email address
        url: mailto:matt@nmt.edu

# Clients information. Shown on Home and About pages.
clients:
  - name: University of Manitoba
    img: uman.jpg
  - name: New Mexico Bureau of Geology and Mineral Resources
    img: bureau_logo_screen.png
  - name: New Mexico Tech
    img: nmtlogo-small.gif
  - name: USGS
    img: USGS.png


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "New Mexico Geochronology Research Laboratory (NMGRL) is a world class Ar-Ar geochronology laboratory located at
New Mexico Bureau of Geology and Mineral Resources. Pychron Labs, LLC is small scientific software consulting firm
specializing in data acquisition and processing noble gas mass spectrometry analyses. "

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO